[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  publish = ".next"
  command = "npm run build"

[context.master]
  command = "npm run build"
  environment = { NODE_ENV = "development" }
  publish = ".next"