[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  publish = ".next"
  command = "npm run build"

[context.master]
  command = "npm run build && echo $APP_ENV"
  environment = { APP_ENV = "development" }
  publish = ".next"